---
title: Chapter 4 Problems
output: html_document
---

**4E1.** The first line $y_i \sim \text{Normal}(\mu,\sigma)$ is the likelihood.

**4E2.** There are two paramaters in the posterior distribution $\mu$ and $\sigma$.

**4E3.** Bayes' Theorem says
$$
\begin{align*}
\text{Pr}(\mu,\sigma|y_i)&\propto\text{Pr}(y_i|\mu,\sigma)\text{Pr}(\mu)\text{Pr}(\sigma) \\
&=\frac{\text{Normal}(y_i|\mu,\sigma)\text{Normal}(\mu|0,10)\text{Exponential}(\sigma|1)}{\int\text{Normal}(y_i|\mu,\sigma)\text{Normal}(\mu|0,10)\text{Exponential}(\sigma|1)\text d\mu\text d\sigma}
\end{align*}
$$

**4E4.** The linear model is the second line $\mu_i=\alpha + \beta x_i$.

**4E5.** There are three parameters in the posterior distribution: $\alpha$, $\beta$, and $\sigma$.

**4M1.** 
```{r}
prior_mu <- rnorm(1e4, mean = 0, sd = 10)
prior_s <- rexp(1e4, rate = 1)
y_prior_pred <- rnorm(1e4, mean = prior_mu, s = prior_s)
hist(y_prior_pred)
```

**4M2.**
```{r eval=FALSE}
quap(
    alist(
        y ~ dnorm(mu, sigma),
        mu ~ dnorm(0, 10),
        sigma ~ dexp(1)
    )
)
```

**4M3.**
$$
\begin{align*}
y_i &\sim \text{Normal}(\mu, \sigma) \\
\mu_i &= \alpha + \beta x_i \\
\alpha &\sim \text{Normal}(0, 10) \\
\beta &\sim \text{Uniform}(0, 1) \\
\sigma &\sim \text{Exponential}(1)
\end{align*}
$$